# Generated by Django 2.2.7 on 2019-11-22 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='n/a', max_length=100)),
                ('description', models.CharField(default='n/a', max_length=255)),
                ('location', models.CharField(default='n/a', max_length=100)),
                ('farm_pic_url', models.CharField(default='n/a', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='n/a', max_length=100)),
                ('description', models.CharField(default='n/a', max_length=255)),
                ('location', models.CharField(default='n/a', max_length=100)),
                ('rest_pic_url', models.CharField(default='n/a', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='n/a', max_length=100)),
                ('description', models.CharField(default='n/a', max_length=255)),
                ('price', models.IntegerField(default='n/a')),
                ('unit', models.CharField(default='lbs', max_length=20)),
                ('total_quantity', models.IntegerField(default='0')),
                ('order_quantity', models.IntegerField(default='0')),
                ('product_pic_url', models.CharField(default='n/a', max_length=255)),
                ('tag', models.CharField(default='n/a', max_length=30)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='freshly_grown_app.Farm')),
            ],
        ),
    ]
