# Generated by Django 2.2.7 on 2019-11-25 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freshly_grown_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='order_quantity',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='total_quantity',
            field=models.CharField(default='0', max_length=20),
        ),
    ]
